version: '2'
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: dev_notex
      POSTGRES_USER: dev_notex
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: dev_notex
      DB_USERNAME: dev_notex
      DB_HOSTNAME: postgres
    links:
      - postgres

volumes:
  postgres:
    driver: local
  app:
    driver: local
